### ISSUE TITLE
imageio-batik support?

### ISSUE THREAD

**Issue by NMichas** [Maurice-Betzel/twelvemonkeys-osgi#1]
Hi Maurice, thanks for publishing this, it helped us a lot with twelvemonkeys in our Karaf. I was wondering whether you have also tried integrating `imageio-batik` from twelvemonkeys? I tried to extend the producer with:
```
<dependency>
      <groupId>com.twelvemonkeys.imageio</groupId>
      <artifactId>imageio-batik</artifactId>
      <version>${twelvemonkeys.version}</version>
      <scope>compile</scope>
    </dependency>
```
but SVG never came up in the list of supported ImageReaders.

Thanks!

**Comment by Maurice-Betzel** [comment]
Oh dear, i remember having left out some parts because of issues i cannot remember. I have to think about it.

**Comment by Maurice-Betzel** [comment]
Take a look at the pom of the imagio-batik maven vector, it has a lot of dependencies you will have to provide. For simplicity add these dependencies to the publisher depenencies, also with compile scope, and add the fqn to the Embed-Dependency declaration to put them on the classpath. Also check for transitive dependencies. After a maven build check if the bundle contains all the required dependencies and try to deploy. If successfull create a pull request :)

**Comment by NMichas** [comment]
Just for anyone else trying this ending up on this repo... After spending half a day chasing the dependencies :) there are mainly two issues:
1/ https://github.com/haraldk/TwelveMonkeys/blob/e8d427ae5f19e566d098b61decd6bd0bf037771f/imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGProviderInfo.java#L42 is doing a classloader lookup which doesn't work on OSGi. I patched this removing the lookup and SVG reader now is being picked up fine.
2/ Apache Batik is not OSGi-ready and considering the myriad dependencies it has, after having wrapped more than 10 external deps my bundle is still not working when trying to read SVGs (complaining it can't find classes I suppose to have already wrapped and made available). There is a Batik OSGi-fied version from ServiceMix but this is also missing lots of deps.

I might end up doing the SVG conversion on another non-OSGi layer of my app but that's one extra moving part I'd like to avoid.

**Comment by NMichas** [comment]
> Take a look at the pom of the imagio-batik maven vector, it has a lot of dependencies you will have to provide. For simplicity add these dependencies to the publisher depenencies, also with compile scope, and add the fqn to the Embed-Dependency declaration to put them on the classpath. Also check for transitive dependencies. After a maven build check if the bundle contains all the required dependencies and try to deploy. If successfull create a pull request :)

I though of that but this is just so not-OSGi :) I might actually try this before completely giving up though ;)

**Comment by Maurice-Betzel** [comment]
Thx for the elaborate explanation, i did use the batik libs from servicemix with Apache FOP. You might take up research there.
